spring.application.name=weatherly

# Server configuration
server.port=8080

# Weather API configuration
weather.api.url=https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline
weather.api.key=${WEATHER_API_KEY:dummy_api_key_for_development}

# Cache configuration
# 12 hours in milliseconds
app.cache.time-to-live=43200000
