spring.application.name=weatherly

# Server configuration
server.port=8080

# Weather API configuration
weather.api.url=https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline
weather.api.key=${WEATHER_API_KEY:DUMMY_KEY_FOR_DEVELOPMENT}

# Redis configuration
spring.redis.host=${REDIS_HOST:localhost}
spring.redis.port=${REDIS_PORT:6379}
spring.cache.type=redis

# Cache configuration
# 12 hours in milliseconds
app.cache.time-to-live=43200000

# API key authentication
app.api-key.header-name=X-API-Key
app.api-key.value=${WEATHER_API_KEY:}
app.api-key.enabled=${APP_API_KEY_ENABLED:false}

# Rate limiting configuration
app.rate-limit.capacity=20
app.rate-limit.refill-tokens=10
app.rate-limit.refill-duration=1

# Actuator configuration
management.endpoints.web.exposure.include=health,info,metrics,prometheus,caches,env
management.endpoint.health.show-details=when_authorized
management.info.env.enabled=true
management.endpoint.prometheus.enabled=true

# Application info for Actuator
info.app.name=Weatherly API
info.app.description=A Spring Boot API that fetches weather data, caches with Redis, and manages configurations securely
info.app.version=1.0.0
info.app.java.version=${java.version}
info.app.spring-boot.version=${spring-boot.version}

# OpenAPI/Swagger configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
