name: weatherly-api
services:
  - name: api
    github:
      repo: mdhamed238/weatherly
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    http_port: 8080
    instance_size_slug: basic-xxs
    envs:
      - key: WEATHER_API_KEY
        value: "${WEATHER_API_KEY}"
        scope: RUN_TIME
        type: SECRET
      - key: APP_API_KEY_ENABLED
        value: "true"
        scope: RUN_TIME
      - key: SERVER_PORT
        value: "8080"
        scope: RUN_TIME
      - key: APP_CACHE_TIME_TO_LIVE
        value: "43200000"
        scope: RUN_TIME
      - key: APP_RATE_LIMIT_CAPACITY
        value: "20"
        scope: RUN_TIME
      - key: APP_RATE_LIMIT_REFILL_TOKENS
        value: "10"
        scope: RUN_TIME
      - key: APP_RATE_LIMIT_REFILL_DURATION
        value: "1"
        scope: RUN_TIME